name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        go: [ 1.12, 1.13, 1.14 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up golang with version ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -v -coverprofile=covprofile ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1.4.2
        with:
          path-to-profile: covprofile
          flag-name: go-${{ matrix.go }}-OS-${{ matrix.os }}
          parallel: true
  finish:
    needs: ci-test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1.4.2
        with:
          parallel-finished: true